In [1]:
import numpy as np

In [3]:
my_vector = np.array([-17, 39, 0, 34, 28, 78])

In [4]:
zero_mod_2 = 0 ==(my_vector % 2)
zero_mod_2

array([False, False,  True,  True,  True,  True])

In [5]:
sub_array = my_vector[zero_mod_2]
sub_array

array([ 0, 34, 28, 78])

In [7]:
sub_array[sub_array > 0]

array([34, 28, 78])