In [1]:
import numpy as np

In [3]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2, 7, 5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [4]:
# Number of Dimensions

my_3D_array.ndim

3

In [5]:
# size Number

my_3D_array.size

70

In [6]:
#data type for each element

my_3D_array.dtype

dtype('int32')

In [7]:
 5 * my_3D_array - 2


array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [ ]:
left_side = np.arange(6).reshape((2, 3))
left_side

In [11]:
right_side = np.arange(15).reshape(3, 5)
right_side

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
np.inner(left_side, right_side)


ValueError: shapes (2,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [13]:
np.dot(left_side, right_side)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

## Operations along axes

In [14]:
my_3D_array
 

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [15]:
my_3D_array.shape

(2, 7, 5)

In [16]:
my_3D_array.sum()

2415

In [17]:
my_3D_array.sum(axis = 1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

# Broadcasting Rules

In [19]:
my_2D_array = np.ones(35, dtype = 'int').reshape((7, 5)) * 3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [25]:
my_random_2D_array = np.random.random((7, 5))
my_random_2D_array

array([[0.1751, 0.6608, 0.7552, 0.1444, 0.0212],
       [0.8108, 0.4338, 0.7401, 0.6456, 0.0717],
       [0.0305, 0.5986, 0.3483, 0.1464, 0.6293],
       [0.295 , 0.0169, 0.4369, 0.9333, 0.7   ],
       [0.33  , 0.6943, 0.3514, 0.6049, 0.2733],
       [0.1269, 0.8007, 0.6434, 0.1296, 0.0104],
       [0.0523, 0.3761, 0.6611, 0.5087, 0.3165]])

In [24]:
np.set_printoptions(precision = 4)
my_3D_array * my_random_2D_array

array([[[ 0.    ,  0.9448,  1.5458,  2.2507,  1.4674],
        [ 1.3049,  1.6469,  4.2016,  5.4929,  0.3544],
        [ 7.4339,  3.8228,  8.7076, 11.6129, 12.7406],
        [ 1.8828,  8.6553, 15.4843,  5.2194,  7.2472],
        [ 2.4405, 14.7406, 17.8601, 19.0993, 19.7018],
        [24.4602, 15.3532,  0.9253, 18.139 ,  2.987 ],
        [26.448 ,  8.3021, 19.9839, 11.7678, 18.8383]],

       [[20.8697, 34.0139, 28.597 , 28.5092, 14.3071],
        [10.439 , 11.2535, 25.2097, 29.5244,  1.7327],
        [33.4525, 15.9863, 34.1048, 42.8783, 44.5919],
        [ 6.276 , 27.5887, 47.3638, 15.3682, 20.5974],
        [ 6.7113, 39.3081, 46.274 , 48.1634, 48.4335],
        [58.7044, 36.021 ,  2.1249, 40.8128,  6.5921],
        [57.3039, 17.6755, 41.8413, 24.2488, 38.2307]]])